# Generated by Django 4.1.3 on 2022-12-03 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
    ]
