# Generated by Django 4.1.3 on 2022-12-04 02:08

import account.utility
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='img/avatar.png', upload_to=account.utility.upload_dir_path),
        ),
    ]
