# Generated by Django 4.1.3 on 2023-01-03 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profile_full_name_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequestIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('path_info', models.CharField(max_length=255)),
                ('attempt_time', models.DateTimeField(auto_now_add=True)),
                ('attempt_numbers', models.PositiveIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
