# Generated by Django 4.1.3 on 2023-01-03 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_userrequestip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequestip',
            name='attempt_numbers',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
