# Generated by Django 4.1.3 on 2023-01-03 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_userrequestip_attempt_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequestip',
            name='attempt_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
