# Generated by Django 4.1.3 on 2022-11-29 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import post.utility


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=post.utility.upload_dir_path)),
                ('caption', models.CharField(blank=True, max_length=2056)),
                ('privacy', models.CharField(choices=[('1', 'PUBLIC'), ('2', 'FOLLOWERS'), ('3', 'PRIVATE')], default=2, max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
